name: spend_diary
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_charts: ^20.3.47
  
  cupertino_icons: ^1.0.8
  intl: ^0.17.0  # Letakkan di sini di bawah dependencies, bukan di bawah flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/expense.png
    - assets/images/spend.png
    - assets/images/manage.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
